### ISSUE TITLE
Pass simple happy-path test

### ISSUE THREAD

**Issue by JordanRickman** [JordanRickman/builder-js#1]
**AC**
- Tests can be run from the command line.
- Tests include a happy-path test of basic functionality - set, add, and build methods.
- Builder class passes all tests.

Depends on #2 

**Sub-Tasks**
- [ ] Import test runner and assertion libraries
- [ ] Write test code
- [ ] Debug and fix until tests pass
